#!/usr/bin/env node

/**
 * Module dependencies.
 */

var program = require('commander');
var _ = require('./index');

program
  .version('0.0.1')
  .option('-p, --peppers', 'Add peppers')
  .option('-P, --pineapple', 'Add pineapple')
  .option('-b, --bbq', 'Add bbq sauce')
  .option('-c, --cheese [type]', 'Add the specified type of cheese [marble]', 'marble')
  .parse(process.argv);

console.log('you ordered a pizza with:');
if (program.peppers) console.log('  - peppers');
if (program.pineapple) console.log('  - pineapple');
if (program.bbq) console.log('  - bbq');
console.log('  - %s cheese', program.cheese);

console.log(program.args);

var operation = program.args[0];
var x = parseInt(program.args[1]);
var y = parseInt(program.args[2]);

if (operation === 'a') {
	console.log('The sum of ' + x + ' and ' + y + ' is ' + _.calc.add(x, y));
}
else if (operation === 's') {
	console.log('The difference between ' + x + ' and ' + y + ' is ' + _.calc.subtract(x, y));
}
else {
	console.log('try again');
};
